### ISSUE TITLE
Footer should be pushed to the bottom

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies-theme#2]
If the window is larger than the site itself, you see whitespace below the footer:

![2015-06-01 at 2 44 pm](https://cloud.githubusercontent.com/assets/1191069/7920454/1cdfda2c-086d-11e5-91f0-b9b4a0f1b124.png)

Ideally the footer would just readjust and "stick" to the bottom - and the extra white-space would be above it.

**Comment by vivgui** [comment]
@econchick please check if fixed
