### ISSUE TITLE
Meetups not showing

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies-theme#4]
We had this issue in current site ([issue](https://github.com/pyladies/pyladies/issues/169)) and was fixed ([PR](https://github.com/pyladies/pyladies/pull/174)).  Perhaps the same fix would help here too.

![2015-06-01 at 2 49 pm](https://cloud.githubusercontent.com/assets/1191069/7920515/a2c701a6-086d-11e5-97ab-fe854fcdeb77.png)

**Comment by vivgui** [comment]
fixed
