### ISSUE TITLE
Collapse footer when on smaller devices

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies-theme#6]
The navbar collapses nicely - could we also collapse the footer? No need to allow for the social links to show, maybe just collapse into the copyright notice.

![2015-06-01 at 3 05 pm](https://cloud.githubusercontent.com/assets/1191069/7920951/1a831f0c-0870-11e5-9dc2-378d555c3e7d.png)

**Comment by econchick** [comment]
Hmm not sure if this is also possible but perhaps when the navbar collapses, to change the "pyladies" logo at the top from the wordmark to the "geek girl" - the same geek girl as the favicon.

**Comment by vivgui** [comment]
fixed
