### ISSUE TITLE
Italics color doesn't match theme color

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies-theme#8]
This was found in `/resources`, and the actual post is `_posts/2014/2014-08-26-speaking-pycon.md`.  Looks like italics is still taking after the old color theme maybe?
![2015-06-01 at 3 15 pm](https://cloud.githubusercontent.com/assets/1191069/7921112/31077416-0871-11e5-97d9-fa7dd54f7bcb.png)

**Comment by vivgui** [comment]
fixed
